# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci && npm run prepare

# Production image
FROM node:lts-alpine AS production
WORKDIR /app

# Copy built artifacts and package files
COPY --from=builder /app/lib ./lib
COPY package.json package-lock.json ./

# Install only production dependencies without running scripts
RUN npm ci --omit=dev --ignore-scripts

# Start the MCP server
CMD ["node", "lib/index.mjs"]
